config/routes.rb
Rails.application.routes.draw do

  get 'suburbs/new'

  get 'cuisines/new'

  root :to => 'pages#home'

  resources :users, :only => [:new, :create]

  get '/login' => 'session#new' #sign in form
  post '/login' => 'session#create' #sign in action
  delete '/login' => 'session#destroy' #sign out
  # See rails guide for routing, in particular nested routes

  resources :restaurants
  resources :cuisines
  resources :suburbs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :restaurants
  # has_many :suburbs, :through => :resturants
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :cuisine, :optional => true
  belongs_to :suburb, :optional => true
end

app/models/suburb.rb
class Suburb < ApplicationRecord
  has_many :restaurants
  #has_many :cuisines, :through => :restaurants
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, :presence => true, :uniqueness => true #can not create new login without email address or duplicates

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :fetch_user

  private
  def fetch_user
      @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
      session[:user_id] = nil unless @current_user.present?
    end
  end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def index
    @cuisines = Cuisine.all.order(:created_at)
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    cuisine = Cuisine.create cuisine_params
    redirect_to cuisine
  end

  def edit
    @cuisine = Cuisine.find params[:id]
  end

  def update
    cuisine = Cuisine.find params[:id]
    cuisine.update cuisine_params
    redirect_to cuisine
  end

  def show
    @cuisine = Cuisine.find params[:id]
  end

  def destroy
    cuisine = Cuisine.find params[:id]
    cuisine.destroy
    redirect_to cuisines_path
  end

  private
  def cuisine_params
    params.require(:cuisine).permit(:name, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all.order(:created_at)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    restaurant = Restaurant.create restaurant_params
    redirect_to restaurant
  end

  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def update
    restaurant = Restaurant.find params[:id]
    restaurant.update restaurant_params
    redirect_to restaurant
  end

  def show
    @restaurant = Restaurant.find params[:id]
  end

  def destroy
    restaurant = Restaurant.find params[:id]
    restaurant.destroy
    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :cuisine_id, :suburb_id, :price, :image)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    @user = User.find_by :email => params[:email]
    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/suburbs_controller.rb
class SuburbsController < ApplicationController
  def index
    @suburbs = Suburb.all
  end

  def new
    @suburb = Suburb.new
  end

  def create
    suburb = Suburb.create suburb_params
    redirect_to suburb
  end

  def edit
    @suburb = Suburb.find params[:id]
  end

  def update
    suburb = Suburb.find params[:id]
    suburb.update suburb_params
    redirect_to suburb
  end

  def show
    @suburb = Suburb.find params[:id]
  end

  def destroy
    suburb = Suburb.find params[:id]
    suburb.destroy
    redirect_to suburbs_path
  end

  private
  def suburb_params
    params.require(:suburb).permit(:name)
  end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_path #it worked!
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/suburbs_helper.rb
module SuburbsHelper
end

app/views/cuisines/_form.html.erb
<%= form_for @cuisine do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>

  <%= f.label :image %>
  <%= f.url_field :image %>

  <%= f.submit %>
<% end %>

app/views/cuisines/edit.html.erb
<h1>Edit Cuisine</h1>

<%= render :partial => 'form' %>

app/views/cuisines/index.html.erb
<h1>All Cuisines</h1>

<div class="gallery">
  <% @cuisines.each do |cuisine| %>
    <div class="wrapper">
    <%= link_to image_tag(cuisine.image, :class => 'img-fluid cuisine-thumbnail img-thumbnail', :alt => cuisine.name), cuisine, :name => cuisine.name %>
      <div class="text">
        <p><%=  cuisine.name %></p>
      </div>
      </div>
    <% end %>
</div>

app/views/cuisines/new.html.erb
<h1>New Cuisine</h1>

<%= render :partial => 'form' %>

app/views/cuisines/show.html.erb
<h1><%= @cuisine.name %></h1>

<div class="gallery">
<%= image_tag(@cuisine.image, :alt => @cuisine.name, :class => 'img-fluid show-cuisine img-thumbnail') %>
</div>
<% unless @cuisine.restaurants.empty? %>
  <h2>Restaurants</h2>
  <div class="gallery">
  <% @cuisine.restaurants.each do |restaurant| %>
    <div class="wrapper">
    <%= link_to image_tag(restaurant.image, :alt => restaurant.name, :class => 'img-thumbnail restaurant-thumbnail'), restaurant, :name => restaurant.name %>
    <div class="text">
      <p><%= restaurant.name %></p>
    </div>
  </div>
  <% end %>
  </div>
<% end %>

<div class="controls">
  <%= link_to 'Edit', edit_cuisine_path(@cuisine) %>
  <%= link_to 'Delete', @cuisine, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Get Fat</title>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="https://www.freefavicon.com/freefavicons/food/summer-hot-dog-152-70699.png">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar">
      <% if @current_user.present? %>
        <%= link_to 'Home', root_path %>
        <%= link_to 'Restaurants', restaurants_path %>
        <%= link_to 'New Restaurants', new_restaurant_path %>
        <%= link_to 'Cuisines', cuisines_path %>
        <%= link_to 'New Cuisines', new_cuisine_path %>
        <%= link_to 'Location', suburbs_path %>
        <%= link_to 'New Locations', new_suburb_path %>
        <%= link_to "Sign Out #{ @current_user.email}", login_path, :method => 'delete' %>
        <% else %>
        <%= link_to 'Home', root_path %>
        <%= link_to 'Sign Up', new_user_path %>
        <%= link_to 'Sign In', login_path  %>
        <%= link_to 'Restaurants', restaurants_path %>
        <%= link_to 'Cuisines', cuisines_path %>
        <%= link_to 'Location', suburbs_path %>
        <% end %>
    </nav>
    <div class="container">
      <div class="fill">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>&#127828; Get Fat &#127856;<br>&#127837; Or &#127829;<br>&#127836; Die Trying &#127849;</h1>

<div class="home">
<p>The ultimate Sydney food guide unless you like French, try Bonny for that.</p>
<br>
<p>Add your foodie adventures to the database otherwise I'll run out of places to eat.</p>
<br>
<% if @current_user.present? %>
Welcome back <%= @current_user.email %>
<% end %>
</div>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>

  <%= f.label :cuisine_id %>
  <%= f.select :cuisine_id, Cuisine.pluck(:name, :id), :include_blank => true %>

  <%= f.label :suburb_id %>
  <%= f.select :suburb_id, Suburb.pluck(:name, :id), :include_blank => true %>

  <%= f.label :price %>
  <%= f.select(:price, ['$', '$$', '$$$'], :include_blank => true) %>

  <%= f.label :image %>
  <%= f.url_field :image %>

  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render :partial => 'form' %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>

<div class="gallery">
  <% @restaurants.each do |restaurant| %>
    <div class="wrapper">
    <%= link_to image_tag(restaurant.image, :class => 'img-fluid restaurant-thumbnail img-thumbnail', :alt => restaurant.name), restaurant, :name => restaurant.name %>
    <div class="text">
      <p><%= restaurant.name %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render :partial => 'form' %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<div class="gallery">
<%= image_tag(@restaurant.image, :alt => @restaurant.name, :class => 'img-fluid show-restaurant img-thumbnail') %>
</div>
<div class="description">
  <% if @restaurant.cuisine.present? %>
  Cuisine: <%= link_to @restaurant.cuisine.name, @restaurant.cuisine %>
  <% end %><br>
  Location: <% if @restaurant.suburb.present? %>
  <%= link_to @restaurant.suburb.name, @restaurant.suburb %>
  <% end %><br>
  <% if @restaurant.price.present? %>
  Price: <%= @restaurant.price %>
  <% end %>
</div>

<div class="controls">
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
  <%= link_to 'Delete', @restaurant, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
</div>

app/views/session/new.html.erb
<h1>Log in</h1>

<h2><%= flash[:error] %></h2>

<%=  form_tag login_path do %>
  <%= label_tag :email %>
  <%= email_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag "Log in" %>
<% end %>

app/views/suburbs/_form.html.erb
<%= form_for @suburb do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true %>

  <%= f.submit %>
<% end %>

app/views/suburbs/edit.html.erb
<h1>Edit Suburb</h1>

<%= render :partial => 'form' %>

app/views/suburbs/index.html.erb
<h1>All Suburbs</h1>

<% @suburbs.each do |suburb| %>
  <%= link_to suburb.name, suburb, :name => suburb.name, :class => 'suburb' %> 
<% end %>

app/views/suburbs/new.html.erb
<h1>New Suburb</h1>

<%= render :partial => 'form' %>

app/views/suburbs/show.html.erb
<h1><%= @suburb.name %></h1>

<% unless @suburb.restaurants.empty? %>
  <h2>Restaurants</h2>
  <div class="gallery">
  <% @suburb.restaurants.each do |restaurant| %>
    <div class="wrapper">
    <%= link_to image_tag(restaurant.image, :alt => restaurant.name, :class => 'img-thumbnail restaurant-thumbnail'), restaurant, :name => restaurant.name %>
    <div class="text">
      <p><%= restaurant.name %></p>
    </div>
  </div>
  <% end %>
  </div>
<% end %>

</ul>

<div class="controls">
  <%= link_to 'Edit', edit_suburb_path(@suburb) %>
  <%= link_to 'Delete', @suburb, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors.any? %>
<ol>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg.capitalize %></li>
  <% end %>
</ol>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Sign up!" %>
<% end %>